<h1> Exercise 5</h1>
<p>Onur BOZKURTOĞLU</p>
<p>20170808044</p>
<h2>9    Numpy</h2>
<h3>Exercise 9.5: Singular values</h3>
<p><b> Generate an n × n matrix, denoted by C, where each entry is 1 with probability p and 0 otherwise. Use
the linear algebra library of Scipy to compute the singular values of C. What can you say about the
relationship between n, p and the largest singular value? </b></p>

In [97]:
import numpy as np
from random import choices

size = (200,200)
C = np.zeros(size)
probability = 0.4

for i in range(200):  
    for j in range(200):
        C[i][j] = np.random.choice(np.arange(2), p = [1 - probability, probability])
print(C)

[[0. 1. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 1. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 ...
 [1. 0. 1. ... 1. 1. 1.]
 [0. 1. 0. ... 0. 0. 1.]
 [1. 0. 1. ... 0. 0. 1.]]


<h2>10    Scipy</h2>
<h3>Exercise 10.1: Least squares</h3>
<p><b> Generate matrix A elements of R^m×n with m > n. Also generate some vector b elements of R^m. </b></p>
<p><b> Now find x = arg minx ||Ax − b||2. </b></p>
<p><b> Print the norm of the residual. </b></p>

In [91]:
from scipy.optimize import nnls
from numpy import random

In [103]:
def least_squares(m, n):
    size = (m,n)
    b = np.zeros(m)
    for i in range(m):
        b[i] = np.random.randint(100)
    A = np.zeros(size)
    for i in range(m):
        for j in range(n):
            A[i][j] = np.random.randint(100)
    x = nnls(A, b)
    return x[1]

In [104]:
least_squares(10,4)

83.86543202425288