<h1> Exercise 5</h1>
<p>Onur BOZKURTOĞLU</p>
<p>20170808044</p>
<h2>9    Numpy</h2>
<h3>Exercise 9.5: Singular values</h3>
<p><b> Generate an n × n matrix, denoted by C, where each entry is 1 with probability p and 0 otherwise. Use
the linear algebra library of Scipy to compute the singular values of C. What can you say about the
relationship between n, p and the largest singular value? </b></p>

In [75]:
import numpy as np
from random import choices

size = (200,200)
C = np.zeros(size)
probability = 0.4

for i in range(200):  
    for j in range(200):
        C[i][j] = np.random.choice(np.arange(2), p = [probability, 1 - probability])
print(C)

[[1. 1. 0. ... 1. 1. 1.]
 [1. 1. 0. ... 1. 0. 0.]
 [0. 1. 1. ... 0. 0. 1.]
 ...
 [1. 1. 0. ... 0. 1. 1.]
 [0. 0. 1. ... 0. 0. 1.]
 [0. 0. 1. ... 0. 1. 1.]]
